[project]
name = "deepfinnk-research-agent"
version = "0.1.0"
description = "AI-powered financial agent that helps users manage their finances using their Bunq account."
authors = [
    { name = "Victor Hornet" },
    { name = "Andrea Onofrei" },
    { name = "Yulin Chen" },
    { name = "Denis Krylov" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "camel-ai[owl]==0.2.50",
    "docx2markdown>=0.1.1",
    "flasgger>=0.9.7.1",
    "flask>=3.1.0",
    "xmltodict>=0.14.2",
]
